-- MySQL Script generated by MySQL Workbench
-- jeu. 27 sept. 2018 22:03:19 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trobada
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `trobada` ;

-- -----------------------------------------------------
-- Schema trobada
--
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trobada` DEFAULT CHARACTER SET utf8 ;
USE `trobada` ;





-- phpMyAdmin SQL Dump
-- version 4.5.4.1deb2ubuntu2
-- http://www.phpmyadmin.net
--
-- Client :  localhost
-- Généré le :  Jeu 04 Octobre 2018 à 10:41
-- Version du serveur :  5.7.22-0ubuntu0.16.04.1
-- Version de PHP :  7.2.9-1+ubuntu16.04.1+deb.sury.org+1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `trobada`
--

-- --------------------------------------------------------

--
-- Structure de la table `checked_transactions`
--

CREATE TABLE `checked_transactions` (
  `id` int(11) UNSIGNED NOT NULL,
  `checked` tinyint(1) DEFAULT '0',
  `transactions_id` int(11) UNSIGNED NOT NULL,
  `users_id` int(11) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Structure de la table `credits_amounts`
--

CREATE TABLE `credits_amounts` (
  `id` int(11) UNSIGNED NOT NULL,
  `users_id` int(11) UNSIGNED NOT NULL,
  `amount` int(11) UNSIGNED ZEROFILL DEFAULT NULL,
  `approved` tinyint(1) DEFAULT NULL,
  `success` tinyint(1) DEFAULT NULL,
  `cus_id` varchar(255) DEFAULT NULL,
  `ch_id` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `message` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Structure de la table `events`
--

CREATE TABLE `events` (
  `id` int(11) UNSIGNED NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text,
  `users_id` int(11) UNSIGNED NOT NULL,
  `not_deletable` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Structure de la table `events_places`
--

CREATE TABLE `events_places` (
  `id` int(11) UNSIGNED NOT NULL,
  `starting_date` datetime DEFAULT NULL,
  `ending_date` datetime DEFAULT NULL,
  `place` varchar(255) DEFAULT NULL,
  `events_id` int(11) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Structure de la table `events_registrations`
--

CREATE TABLE `events_registrations` (
  `users_id` int(11) UNSIGNED NOT NULL,
  `events_places_id` int(11) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Structure de la table `partners`
--

CREATE TABLE `partners` (
  `id` int(11) UNSIGNED NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` text,
  `logo_location` varchar(255) DEFAULT NULL,
  `site_url` varchar(255) DEFAULT NULL,
  `partners_categories_id` int(10) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Structure de la table `partners_categories`
--

CREATE TABLE `partners_categories` (
  `id` int(10) UNSIGNED NOT NULL,
  `name_categories` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Structure de la table `products`
--

CREATE TABLE `products` (
  `id` int(11) UNSIGNED NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` text,
  `price` double UNSIGNED NOT NULL,
  `users_id` int(11) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Structure de la table `products_qrcode`
--

CREATE TABLE `products_qrcode` (
  `id` int(11) UNSIGNED NOT NULL,
  `products_id` int(11) UNSIGNED NOT NULL,
  `events_id` int(11) UNSIGNED NOT NULL,
  `qrcode_phrase` varchar(255) DEFAULT NULL,
  `qrcode_img_path` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Structure de la table `roles`
--

CREATE TABLE `roles` (
  `id` int(11) UNSIGNED NOT NULL,
  `short_name` varchar(20) DEFAULT NULL,
  `long_name` varchar(50) DEFAULT NULL,
  `description` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Contenu de la table `roles`
--

INSERT INTO `roles` (`id`, `short_name`, `long_name`, `description`) VALUES
(1, 'ADM', 'administrateur', 'Le Boss'),
(2, 'FEST', 'festivalier', 'Ceux qui paient'),
(3, 'COM', 'commerçant', 'Ceux qui vendent'),
(4, 'ORG', 'organisateur', 'Ceux qui organisent');

-- --------------------------------------------------------

--
-- Structure de la table `transactions`
--

CREATE TABLE `transactions` (
  `id` int(11) UNSIGNED NOT NULL,
  `amount` double(8,2) UNSIGNED DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `description` text,
  `id_fest` int(11) UNSIGNED NOT NULL,
  `id_com` int(11) UNSIGNED NOT NULL,
  `events_places_id` int(11) UNSIGNED NOT NULL,
  `checked` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure de la table `transactions_entries`
--

CREATE TABLE `transactions_entries` (
  `id` int(11) UNSIGNED NOT NULL,
  `products_id` int(11) UNSIGNED NOT NULL,
  `products_name` varchar(255) NOT NULL,
  `price` double DEFAULT NULL,
  `qty` int(5) DEFAULT NULL,
  `transactions_id` int(11) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Structure de la table `users`
--

CREATE TABLE `users` (
  `id` int(11) UNSIGNED NOT NULL,
  `pseudo` varchar(20) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `secret_code` varchar(255) DEFAULT NULL,
  `firstname` varchar(100) DEFAULT NULL,
  `lastname` varchar(100) DEFAULT NULL,
  `balance` float DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `post_code` int(11) UNSIGNED DEFAULT NULL,
  `town` varchar(255) DEFAULT NULL,
  `roles_id` int(11) UNSIGNED NOT NULL,
  `cus_id` varchar(255) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Contenu de la table `users`
--

INSERT INTO `users` (`id`, `pseudo`, `email`, `password`, `secret_code`, `firstname`, `lastname`, `balance`, `address`, `post_code`, `town`, `roles_id`, `cus_id`, `company_name`) VALUES
(1, 'admin', 'admin@admin.com', '$2y$10$5bjkyKbM.z2.IkEdFldFg.jnOhqUqYPoZirt2Nua4RmQhB0AtFh8a', NULL, 'Wood', 'MAWOGANI', NULL, 'Au pied du Canigou', 66000, 'Perpignan', 1, NULL, 'TROBADA'),
(2, 'festi', 'festi@festi.fes', '$2y$10$049kMRylJv0/UMioap/q5urzBCgHxt1AZZpKf/r5RUKqGFmTvYGJe', '$2y$10$CjqlKxl5z862N5I9mc0fSe3IQuG9xpPPPdIuss7PfRQqFHI4hAYMm', 'tivalier', 'Fes', 60, '1 rue des festivités', 34500, 'Béziers', 2, 'cus_DiWm5yv0vrZR5B', NULL),
(3, 'comme', 'comme@comme.com', '$2y$10$IrD8o4x8NLt3X9v2RBsYMez5ODk5oZdCoonGeNfIgFJERHUaGD26S', NULL, 'comme', 'Rcant', NULL, '1 rue des commerçants', 38000, 'Grenoble', 3, NULL, NULL),
(4, 'organ', 'organe@sdfsd.mp', '$2y$10$RSrWZnKrVqr3oDLoI6b1Ue31n9U5A/VhrCEALZLn.HFu0ak8MyTlu', NULL, 'Jean-Judicaël', 'REDIVO', NULL, '1 rue de la poupée qui tousse', 34500, 'Béziers', 4, NULL, 'Les courgettes');

--
-- Index pour les tables exportées
--

--
-- Index pour la table `checked_transactions`
--
ALTER TABLE `checked_transactions`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_checked_transactions_transactions1` (`transactions_id`),
  ADD KEY `fk_checked_transactions_users1` (`users_id`);

--
-- Index pour la table `credits_amounts`
--
ALTER TABLE `credits_amounts`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_credits_amounts_users1` (`users_id`);

--
-- Index pour la table `events`
--
ALTER TABLE `events`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_events_users1` (`users_id`);

--
-- Index pour la table `events_places`
--
ALTER TABLE `events_places`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_events_places_events1` (`events_id`);

--
-- Index pour la table `events_registrations`
--
ALTER TABLE `events_registrations`
  ADD KEY `fk_events_has_users_users1` (`users_id`),
  ADD KEY `fk_events_registrations_events_places1` (`events_places_id`);

--
-- Index pour la table `partners`
--
ALTER TABLE `partners`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_partners_partners_categories1` (`partners_categories_id`);

--
-- Index pour la table `partners_categories`
--
ALTER TABLE `partners_categories`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_products_users1` (`users_id`);

--
-- Index pour la table `products_qrcode`
--
ALTER TABLE `products_qrcode`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_products_has_events_products1` (`products_id`),
  ADD KEY `fk_products_has_events_events1` (`events_id`);

--
-- Index pour la table `roles`
--
ALTER TABLE `roles`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `transactions`
--
ALTER TABLE `transactions`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_transactions_users1` (`id_fest`),
  ADD KEY `fk_transactions_users2` (`id_com`),
  ADD KEY `fk_transactions_events_places1` (`events_places_id`);

--
-- Index pour la table `transactions_entries`
--
ALTER TABLE `transactions_entries`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_transactions_entries_products1` (`products_id`),
  ADD KEY `fk_transactions_entries_transactions1` (`transactions_id`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `pseudo_UNIQUE` (`pseudo`),
  ADD UNIQUE KEY `email_UNIQUE` (`email`),
  ADD KEY `fk_users_roles` (`roles_id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `checked_transactions`
--
ALTER TABLE `checked_transactions`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT pour la table `credits_amounts`
--
ALTER TABLE `credits_amounts`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
--
-- AUTO_INCREMENT pour la table `events`
--
ALTER TABLE `events`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
--
-- AUTO_INCREMENT pour la table `events_places`
--
ALTER TABLE `events_places`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
--
-- AUTO_INCREMENT pour la table `partners`
--
ALTER TABLE `partners`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;
--
-- AUTO_INCREMENT pour la table `partners_categories`
--
ALTER TABLE `partners_categories`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
--
-- AUTO_INCREMENT pour la table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=106;
--
-- AUTO_INCREMENT pour la table `products_qrcode`
--
ALTER TABLE `products_qrcode`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT pour la table `roles`
--
ALTER TABLE `roles`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
--
-- AUTO_INCREMENT pour la table `transactions`
--
ALTER TABLE `transactions`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;
--
-- AUTO_INCREMENT pour la table `transactions_entries`
--
ALTER TABLE `transactions_entries`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=59;
--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=58;
--
-- Contraintes pour les tables exportées
--

--
-- Contraintes pour la table `checked_transactions`
--
ALTER TABLE `checked_transactions`
  ADD CONSTRAINT `fk_checked_transactions_transactions1` FOREIGN KEY (`transactions_id`) REFERENCES `transactions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_checked_transactions_users1` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table `credits_amounts`
--
ALTER TABLE `credits_amounts`
  ADD CONSTRAINT `fk_credits_amounts_users1` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table `events`
--
ALTER TABLE `events`
  ADD CONSTRAINT `events_ibfk_1` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table `events_places`
--
ALTER TABLE `events_places`
  ADD CONSTRAINT `fk_events_places_events` FOREIGN KEY (`events_id`) REFERENCES `events` (`id`) ON DELETE CASCADE;

--
-- Contraintes pour la table `events_registrations`
--
ALTER TABLE `events_registrations`
  ADD CONSTRAINT `fk_events_has_users_users1` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_events_registrations_events_places1` FOREIGN KEY (`events_places_id`) REFERENCES `events_places` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;

--
-- Contraintes pour la table `partners`
--
ALTER TABLE `partners`
  ADD CONSTRAINT `fk_partners_partners_categories1` FOREIGN KEY (`partners_categories_id`) REFERENCES `partners_categories` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table `products`
--
ALTER TABLE `products`
  ADD CONSTRAINT `fk_products_users1` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table `products_qrcode`
--
ALTER TABLE `products_qrcode`
  ADD CONSTRAINT `fk_products_has_events_events1` FOREIGN KEY (`events_id`) REFERENCES `events` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_products_has_events_products1` FOREIGN KEY (`products_id`) REFERENCES `products` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table `transactions`
--
ALTER TABLE `transactions`
  ADD CONSTRAINT `fk_transactions_events_places1` FOREIGN KEY (`events_places_id`) REFERENCES `events_places` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_transactions_users1` FOREIGN KEY (`id_fest`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_transactions_users2` FOREIGN KEY (`id_com`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table `transactions_entries`
--
ALTER TABLE `transactions_entries`
  ADD CONSTRAINT `fk_transactions_entries_products1` FOREIGN KEY (`products_id`) REFERENCES `products` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_transactions_entries_transactions1` FOREIGN KEY (`transactions_id`) REFERENCES `transactions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Contraintes pour la table `users`
--
ALTER TABLE `users`
  ADD CONSTRAINT `fk_users_roles` FOREIGN KEY (`roles_id`) REFERENCES `roles` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
